version: "3"
services:
   db:
      image: postgres
      environment:
         - "POSTGRES_PASSWORD=docker"
         - "POSTGRES_DB=gostack_gobarber"
      ports:
         - "5432:5432"
      networks:
         - go-barber-network
   pgadmin:
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: "daniell.oliveirra@gmail.com"
         PGADMIN_DEFAULT_PASSWORD: "docker"
      ports:
         - "5430:80"
      networks:
         - go-barber-network

   mongo:
      image: mongo
      ports:
         - "27017:27017"
      networks:
         - go-barber-network
networks:
   go-barber-network:
      driver: bridge
